name: MayaPy Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mortenbohne/cgp-maya:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run pytest
      run: mayapy -m pytest tests/