name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myimage .

    - name: Run Maya PyTests
      run: docker run -v ${{ github.workspace }}:/. cgp-maya pytest -k tests -p mayapy
